import type { CatalogueProduct } from "@/lib/types";

export const categories = [
  "Sparklers",
  "Flower Pots",
  "Ground Chakkars",
  "Rockets",
  "Aerial Shots",
  "Fancy Fountains",
  "Gift Boxes",
  "Family Combos",
];

export const demoProducts: CatalogueProduct[] = [
  {
    id: "demo-1",
    slug: "gold-sparklers-30cm",
    name: "Gold Sparklers 30 cm",
    category: "Sparklers",
    brand: "Gowtham Selection",
    description: "Bright, steady sparklers suited for family celebration packs.",
    packSize: "10 pieces",
    retailPrice: 180,
    mrp: 260,
    availability: "available",
    imageLabel: "✨",
    featured: true,
    lowSound: true,
  },
  {
    id: "demo-2",
    slug: "flower-pot-deluxe",
    name: "Flower Pot Deluxe",
    category: "Flower Pots",
    brand: "Gowtham Selection",
    description: "A colourful fountain-style favourite with a strong visual display.",
    packSize: "10 pieces",
    retailPrice: 320,
    mrp: 480,
    availability: "limited",
    imageLabel: "🌋",
    featured: true,
  },
  {
    id: "demo-3",
    slug: "ground-chakkar-special",
    name: "Ground Chakkar Special",
    category: "Ground Chakkars",
    brand: "Gowtham Selection",
    description: "Fast spinning ground display for open outdoor areas.",
    packSize: "10 pieces",
    retailPrice: 240,
    mrp: 360,
    availability: "available",
    imageLabel: "🌀",
    featured: true,
  },
  {
    id: "demo-4",
    slug: "twelve-shot-aerial",
    name: "12 Shot Aerial",
    category: "Aerial Shots",
    brand: "Festival Series",
    description: "Multi-shot aerial display for larger celebrations and open spaces.",
    packSize: "1 piece",
    retailPrice: 750,
    mrp: 1100,
    availability: "available",
    imageLabel: "🎆",
    featured: true,
  },
  {
    id: "demo-5",
    slug: "family-celebration-combo",
    name: "Family Celebration Combo",
    category: "Family Combos",
    brand: "Gowtham Packs",
    description: "A balanced family assortment covering light, ground and visual items.",
    packSize: "24 assorted items",
    retailPrice: 2499,
    mrp: 3999,
    availability: "available",
    imageLabel: "🎁",
    featured: true,
  },
  {
    id: "demo-6",
    slug: "premium-gift-box",
    name: "Premium Gift Box",
    category: "Gift Boxes",
    brand: "Gowtham Packs",
    description: "A presentation-ready assortment for gifting and family functions.",
    packSize: "36 assorted items",
    retailPrice: 3499,
    mrp: 5499,
    availability: "coming_soon",
    imageLabel: "🧨",
  },
];
